id: AC228488A
title: A Ritual of Blessing and Empowerment for the Female Practice, from the Heart
  Essence of the Vast Expanse
type: translation
pechas:
- I5E16D849
- I00D54B10
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:41:20.852844
  last_modified_at: 2023-01-04 12:41:20.852866
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  I5E16D849/BBA7: '9889'
  I00D54B10/A88D: '9889'
